services:
  mongo:
    image: mongo:7
    container_name: bfl-mongo
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express:1
    restart: unless-stopped
    ports: ["8081:8081"]
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on: [mongo]
volumes:
  mongo_data:
